controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
symfonycasts_verify_email:
    path: /registration/confirmation_email.html.twig
    controller: SymfonyCasts\Bundle\VerifyEmail\Controller\VerifyEmailControllerInterface::verifyEmail
   